### ISSUE TITLE
crates.io, NPM, and docs.rs badges are of unrelated projects

### ISSUE THREAD

**Issue by wackbyte** [RhizomeDB/rs-rhizome#90]
# Summary

- crates.io and docs.rs badges point to [Tamschi/rhizome](https://github.com/Tamschi/rhizome)
- NPM badge points to [benw/rhizome](https://github.com/benw/rhizome)

## Problem

These badges link to unrelated projects.

### Impact

This may confuse the reader.

## Solution

Remove them or replace them with relevant badges.

**Comment by wackbyte** [comment]
Additionally, `rhizome`'s crate manifest uses <https://docs.rs/rhizome> for its documentation, which is the aforementioned unrelated crate. It may be preferable to omit it so that the docs.rs link may be provided automatically.

**Comment by expede** [comment]
haha oh no! The badges were generated from a template; we'll fix those. Thanks for the report!

**Comment by expede** [comment]
@QuinnWilton we may want to rename the various crates to `rhizomedb` or revert to `pomodb` or something

**Comment by QuinnWilton** [comment]
Thanks for pointing this out! I agree that renaming to rhizomedb makes the most sense :)

**Comment by QuinnWilton** [comment]
Thank you! The crates have been renamed and published as `rhizomedb-*`, and the links updated: https://crates.io/crates/rhizomedb
